# Generated by Django 5.2.9 on 2025-12-31 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('calories_per_100g', models.DecimalField(decimal_places=2, help_text='Calories per 100g', max_digits=6)),
                ('protein_per_100g', models.DecimalField(decimal_places=2, help_text='Protein in grams per 100g', max_digits=6)),
                ('carbs_per_100g', models.DecimalField(decimal_places=2, help_text='Carbs in grams per 100g', max_digits=6)),
                ('fat_per_100g', models.DecimalField(decimal_places=2, help_text='Fat in grams per 100g', max_digits=6)),
                ('fiber_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams per 100g (optional)', max_digits=6, null=True)),
                ('sugar_per_100g', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar in grams per 100g (optional)', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.DecimalField(decimal_places=2, help_text='Height (inches)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Weight (lbs)', max_digits=5),
        ),
    ]
