# Generated by Django 5.2.9 on 2026-01-06 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_meal_mealfood_meal_foods_mealplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('contains_dairy', 'Contains Dairy'), ('contains_gluten', 'Contains Gluten'), ('is_vegetarian', 'Vegetarian'), ('is_vegan', 'Vegan'), ('is_meat', 'Meat'), ('is_seafood', 'Seafood'), ('is_egg', 'Contains Egg'), ('is_nut', 'Contains Nuts'), ('is_soy', 'Contains Soy')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Food Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DietaryPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('gluten_free', 'Gluten-Free'), ('dairy_free', 'Dairy-Free'), ('pescatarian', 'Pescatarian'), ('halal', 'Halal'), ('kosher', 'Kosher')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('excluded_categories', models.ManyToManyField(blank=True, help_text='Food categories that violate this dietary pattern', related_name='excluded_in_patterns', to='nutrition.foodcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='food',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Dietary categories/tags for this food', related_name='foods', to='nutrition.foodcategory'),
        ),
        migrations.CreateModel(
            name='UserAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergen_name', models.CharField(help_text='Name of allergen (required if food is not specified)', max_length=200)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='moderate', help_text='Severity of the allergy', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the allergy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food', models.ForeignKey(blank=True, help_text='Specific food in database (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Allergies',
                'ordering': ['allergen_name'],
            },
        ),
        migrations.CreateModel(
            name='UserDietaryPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_notes', models.TextField(blank=True, help_text='Optional custom dietary notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.dietarypattern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pattern__name'],
                'unique_together': {('user', 'pattern')},
            },
        ),
        migrations.CreateModel(
            name='UserFoodDislike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for disliking this food')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_dislikes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['food__name'],
                'unique_together': {('user', 'food')},
            },
        ),
    ]
